version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerfileLocal
    ports:
      - "5173:5173" # Привязываем порт Vite (можно изменить, если у тебя другой порт)
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped